/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx}", "./components/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#582200",
        "outline-variant": "#584237",
        "secondary-fixed": "#ffddb8",
        "on-secondary": "#472a00",
        "surface-bright": "#31394d",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#4edea3",
        "primary-container": "#f97316",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-on-surface": "#283044",
        "on-background": "#dae2fd",
        "on-tertiary": "#003824",
        "primary": "#ffb690",
        "background": "#0b1326",
        "surface-dim": "#0b1326",
        "primary-fixed-dim": "#ffb690",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#2d3449",
        "on-primary-fixed-variant": "#783200",
        "on-primary-fixed": "#341100",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#222a3d",
        "surface": "#0b1326",
        "on-surface-variant": "#e0c0b1",
        "tertiary-container": "#00b07a",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        "on-error": "#690005",
        "surface-variant": "#2d3449",
        "secondary-container": "#ee9800",
        "inverse-primary": "#9d4300",
        "secondary": "#ffb95f",
        "surface-container": "#171f33",
        "tertiary": "#4edea3",
        "on-secondary-container": "#5b3800",
        "on-primary": "#552100",
        "inverse-surface": "#dae2fd",
        "surface-tint": "#ffb690",
        "outline": "#a78b7d",
        "on-surface": "#dae2fd",
        "on-tertiary-container": "#003b26",
        "primary-fixed": "#ffdbca",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#ffb95f",
        "surface-container-low": "#131b2e",
        "surface-container-lowest": "#060e20"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "gutter-lg": "1.75rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "gutter-sm": "0.75rem",
        "space-xl": "2rem",
        "margin-lg": "2.5rem",
        "gutter": "1.25rem",
        "margin": "1.5rem",
        "margin-sm": "1rem"
      },
      fontFamily: {
        "label-lg": ["Cairo"],
        "body-md": ["Cairo"],
        "headline-lg": ["Cairo"],
        "headline-xl": ["Cairo"],
        "display-lg": ["Cairo"],
        "headline-md": ["Cairo"],
        "body-sm": ["Cairo"],
        "body-lg": ["Cairo"],
        "headline-sm": ["Cairo"],
        "display-lg-mobile": ["Cairo"],
        "label-md": ["Cairo"],
        "label-sm": ["Cairo"]
      },
      fontSize: {
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-xl": ["28px", { lineHeight: "38px", fontWeight: "700" }],
        "display-lg": ["40px", { lineHeight: "52px", fontWeight: "800" }],
        "headline-md": ["20px", { lineHeight: "30px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg-mobile": ["30px", { lineHeight: "40px", fontWeight: "800" }],
        "label-md": ["12px", { lineHeight: "18px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "700" }]
      }
    }
  }
};
